name: API CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('api/requirements.txt') }}
      - name: Install dependencies
        run: pip install -r api/requirements.txt
      - name: Lint
        run: flake8 api
      - name: Run tests
        run: pytest api
